# -*- mode: python ; coding: utf-8 -*-

block_cipher = None

a = Analysis(
    ['..\\zsltoimg.py'],
    pathex=['..'],
    binaries=[],
    datas=[],
    hiddenimports=[],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        'tkinter', 'tcl', 'tk',
        'sqlite3',
        'ssl',
        'hashlib',
        'xml',
        'email',
        'html',
        'http',
        'unittest',
        'pydoc',
        'bz2',
        'lzma',
        'multiprocessing',
        'decimal',
        'socket',
        'select',
        'logging',
        'urllib',
        'distutils',
        'setuptools',
        'asyncio',
        'concurrent',
        'tarfile',
        'zipfile',
        'subprocess',
        'argparse',
        'tempfile',
        'plistlib',
        'inspect',
        'difflib',
        'ctypes',
        'fnmatch',
        'gettext',
        'pathlib',
        'shutil',
        'optparse',
        'getopt',
        'bdb',
        'pdb',
        'tty',
        'pydoc_data',
        'platform'
    ],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)
pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='zsltoimg',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
